import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = resolve(HERE, '..');
const TOKENS_PATH = resolve(WEB_ROOT, 'design/tokens.json');
const CSS_OUT = resolve(WEB_ROOT, 'app/tokens.generated.css');
const DART_OUT = resolve(WEB_ROOT, '../magnetrip/lib/theme/app_theme.dart');

export function loadTokens(path = TOKENS_PATH) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function buildCss(t) {
  const c = t.color;
  const root = {
    '--background': c.background,
    '--foreground': c.textPrimary,
    '--card': c.surface,
    '--card-foreground': c.textPrimary,
    '--popover': c.surface,
    '--popover-foreground': c.textPrimary,
    '--primary': c.primary,
    '--primary-foreground': c.primaryForeground,
    '--secondary': c.secondarySurface,
    '--secondary-foreground': c.secondary,
    '--muted': c.secondarySurface,
    '--muted-foreground': c.textSecondary,
    '--accent': c.secondarySurface,
    '--accent-foreground': c.textPrimary,
    '--destructive': c.error,
    '--destructive-foreground': c.errorForeground,
    '--border': c.border,
    '--input': c.border,
    '--ring': c.primary,
    '--brand-accent': c.accent,
    '--brand-accent-foreground': c.accentForeground,
    '--success': c.success,
    '--success-foreground': c.successForeground,
    '--success-surface': c.successSurface,
    '--warning': c.warning,
    '--warning-foreground': c.warningForeground,
    '--text-muted': c.textMuted,
    '--radius': t.radius.md,
  };
  const theme = [
    '--color-brand-accent: var(--brand-accent);',
    '--color-brand-accent-foreground: var(--brand-accent-foreground);',
    '--color-success: var(--success);',
    '--color-success-foreground: var(--success-foreground);',
    '--color-success-surface: var(--success-surface);',
    '--color-warning: var(--warning);',
    '--color-warning-foreground: var(--warning-foreground);',
    '--color-text-muted: var(--text-muted);',
  ].map((l) => '  ' + l).join('\n');
  const vars = Object.entries(root).map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return `/* AUTO-GENERATED by scripts/generate-tokens.mjs — do not edit by hand. */\n@theme inline {\n${theme}\n}\n\n:root {\n${vars}\n}\n`;
}

export function buildDart(t) {
  const c = t.color;
  const argb = (hex) => '0xFF' + hex.replace('#', '').toUpperCase();
  const colorField = (name, hex) => `  static const Color ${name} = Color(${argb(hex)});`;
  const colors = [
    colorField('primary', c.primary),
    colorField('primaryForeground', c.primaryForeground),
    colorField('secondary', c.secondary),
    colorField('secondarySurface', c.secondarySurface),
    colorField('accent', c.accent),
    colorField('background', c.background),
    colorField('surface', c.surface),
    colorField('border', c.border),
    colorField('success', c.success),
    colorField('warning', c.warning),
    colorField('error', c.error),
    colorField('textPrimary', c.textPrimary),
    colorField('textSecondary', c.textSecondary),
    colorField('textMuted', c.textMuted),
    colorField('disabled', c.disabled),
  ].join('\n');
  const px = (v) => String(parseFloat(v));
  const spacing = Object.entries(t.spacing)
    .map(([k, v]) => `  static const double s${k} = ${px(v)};`).join('\n');
  const radii = Object.entries(t.radius)
    .map(([k, v]) => `  static const double ${k.replace('2xl', 'xxl')} = ${px(v)};`).join('\n');
  return `// AUTO-GENERATED by ../magnetrip-web/scripts/generate-tokens.mjs — do not edit by hand.
import 'package:flutter/material.dart';

class MagnetripColors {
  MagnetripColors._();
${colors}
}

class MagnetripSpacing {
  MagnetripSpacing._();
${spacing}
}

class MagnetripRadii {
  MagnetripRadii._();
${radii}
}

ThemeData buildMagnetripTheme() {
  final scheme = ColorScheme.fromSeed(
    seedColor: MagnetripColors.primary,
    primary: MagnetripColors.primary,
    surface: MagnetripColors.surface,
    error: MagnetripColors.error,
    brightness: Brightness.light,
  );
  return ThemeData(
    useMaterial3: true,
    colorScheme: scheme,
    scaffoldBackgroundColor: MagnetripColors.background,
    fontFamily: '${t.font.family}',
  );
}
`;
}

function main() {
  const t = loadTokens();
  writeFileSync(CSS_OUT, buildCss(t));
  mkdirSync(dirname(DART_OUT), { recursive: true });
  writeFileSync(DART_OUT, buildDart(t));
  console.log(`Wrote ${CSS_OUT}\nWrote ${DART_OUT}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
